### ISSUE TITLE
Getting 409 error

### ISSUE THREAD

**Issue by Vulpecula-nl** [marklagendijk/node-transip-dns-cli#15]
When i start my docker container i'm getting this error

```
HTTPError: Response code 409 (Conflict)
    at EventEmitter.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Can you help me resolve it?

**Comment by Vulpecula-nl** [comment]
Opened to fast a issue, after a while the error disappeared and the dns records are adjusted.
